// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import ClientLayout from "@/components/layout/ClientLayout";
// import ReactQueryProvider from "@/components/providers/ReactQueryProvider";

// const inter = Inter({
//     variable: "--font-inter",
//     subsets: [],
// });

// export const metadata: Metadata = {
//     title: "Mein Herz Geschenk",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{ children: React.ReactNode }>) {
//     return (
//         <html lang="en" suppressHydrationWarning>
//             <body className={`${inter.variable} antialiased font-sans`} suppressHydrationWarning>
//                 <ReactQueryProvider>
//                     <ClientLayout>{children}</ClientLayout>
//                 </ReactQueryProvider>
//             </body>
//         </html>
//     );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/layout/ClientLayout";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import NextAuthProvider from "@/components/providers/SessionProvider";

const inter = Inter({
    variable: "--font-inter",
    subsets: [],
});

export const metadata: Metadata = {
    title: "Mein Herz Geschenk",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} antialiased font-sans`} suppressHydrationWarning>
                <NextAuthProvider>
                    <ReactQueryProvider>
                        <ClientLayout>{children}</ClientLayout>
                    </ReactQueryProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}